server:
  port: 9090

spring:
  application:
    name: microservices-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 172.20.10.9:8848
      username: nacos
      password: nacos

    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s
      routes:
        #person服务
        - id: microservices-person-biz
          uri: lb://person-biz
          predicates:
            - Path=/admin/person/**
        #person服务
        - id: microservices-department
          uri: lb://microservices-department
          predicates:
        - Path=/admin/dept/**
        #person服务
        - id: microservices-exam
          uri: lb://microservices-exam
          predicates:
            - Path=/admin/exam/**

      encodeKey: hi!microservices

      discovery:
        locator:
          enabled: true